### ISSUE TITLE
env: node: No such file or directory

### ISSUE THREAD

**Issue by CaptainRuby** [Darmau/koktohay-cms#2]
> strapi@0.1.0 develop
> strapi develop

env: node: No such file or directory
我是不是需要创建一个env文件作为配置文件？我看到config文件夹下有一些读取配置的代码，但我不确定在哪去做这些配置

**Comment by darmau** [comment]
要有一个.env文件，像DATABASE_HOST这些都存在这个文件里

**Comment by darmau** [comment]
其实我建议想抄设计直接拷贝next对应页面的代码就行了，稍微改改就能用。

**Comment by CaptainRuby** [comment]
抱歉，应该先去看博客的，看完了已经跑起来了，现在准备部署下前端，因为不是前端工程师，所以对这两个工程都不是很熟悉。因为我的需求和你是一样，能够放文章，图片，所以还是希望花点时间把它搞起来。

我现在遇到的问题是:
> nomadicoder@0.1.0 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
/bin/sh: pnpm: command not found
event - compiled client and server successfully in 3.3s (919 modules)
wait  - compiling...
event - compiled successfully in 207 ms (834 modules)
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 73 ms (920 modules)
warn  - Fast Refresh had to perform a full reload due to a runtime error.
wait  - compiling / (client and server)...
event - compiled client and server successfully in 321 ms (950 modules)
warn  - Fast Refresh had to perform a full reload due to a runtime error.
error - ApolloError: Failed to parse URL from /graphql
    at new ApolloError (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/errors/errors.cjs:34:28)
    at /Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/core/core.cjs:1853:19
    at both (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/utilities/utilities.cjs:1072:53)
    at /Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/utilities/utilities.cjs:1065:72
    at new Promise (<anonymous>)
    at Object.then (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/utilities/utilities.cjs:1065:24)
    at Object.error (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/utilities/utilities.cjs:1073:49)
    at notifySubscription (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/zen-observable/lib/Observable.js:140:18)
    at onNotify (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/zen-observable/lib/Observable.js:179:3)
    at SubscriptionObserver.error (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/zen-observable/lib/Observable.js:240:7)
    at /Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/utilities/utilities.cjs:1055:68
    at Array.forEach (<anonymous>)
    at iterateObserversSafely (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/utilities/utilities.cjs:1055:25)
    at Object.error (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/utilities/utilities.cjs:1159:21)
    at notifySubscription (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/zen-observable/lib/Observable.js:140:18)
    at onNotify (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/zen-observable/lib/Observable.js:179:3)
    at SubscriptionObserver.error (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/zen-observable/lib/Observable.js:240:7)
    at handleError (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/link/http/http.cjs:296:67)
    at /Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/link/http/http.cjs:582:48 {
  graphQLErrors: [],
  clientErrors: [],
  networkError: TypeError: Failed to parse URL from /graphql
      at Object.fetch (node:internal/deps/undici/undici:11413:11) {
    [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
        at new NodeError (node:internal/errors:399:5)
        at URL.onParseError (node:internal/url:566:9)
        at new URL (node:internal/url:646:5)
        at new Request (node:internal/deps/undici/undici:7002:25)
        at fetch2 (node:internal/deps/undici/undici:10554:25)
        at Object.fetch (node:internal/deps/undici/undici:11411:18)
        at fetch (node:internal/process/pre_execution:230:25)
        at /Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/link/http/http.cjs:570:13
        at new Subscription (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/zen-observable/lib/Observable.js:197:34)
        at Observable.subscribe (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/zen-observable/lib/Observable.js:279:14)
        at Object.complete (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/utilities/utilities.cjs:1184:43)
        at Concast.start (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/utilities/utilities.cjs:1211:23)
        at new Concast (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/utilities/utilities.cjs:1203:19)
        at QueryManager.getObservableFromLink (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/core/core.cjs:1788:35)
        at QueryManager.getResultsFromLink (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/core/core.cjs:1828:40)
        at resultsFromLink (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/core/core.cjs:2005:58)
        at QueryManager.fetchQueryByPolicy (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/core/core.cjs:2031:21)
        at fromVariables (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/core/core.cjs:1879:40)
        at QueryManager.fetchQueryObservable (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/core/core.cjs:1894:15)
        at QueryManager.fetchQuery (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/core/core.cjs:1497:21)
        at QueryManager.query (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/core/core.cjs:1582:21)
        at ApolloClient.query (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/core/core.cjs:2203:34)
        at getServerSideProps (webpack-internal:///./pages/index.tsx:192:84)
        at /Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/next/dist/server/render.js:508:110
        at /Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/next/dist/server/lib/trace/tracer.js:66:32
        at NoopContextManager.with (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7054)
        at ContextAPI.with (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:517)
        at NoopTracer.startActiveSpan (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18022)
        at ProxyTracer.startActiveSpan (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18782)
        at runWithContext (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/next/dist/server/lib/trace/tracer.js:60:164)
        at NextTracerImpl.trace (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/next/dist/server/lib/trace/tracer.js:61:16)
        at Object.renderToHTML (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/next/dist/server/render.js:508:51)
        at async doRender (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/next/dist/server/base-server.js:809:34)
        at async cacheEntry1.responseCache.get.incrementalCache.incrementalCache (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/next/dist/server/base-server.js:929:28)
        at async /Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/next/dist/server/response-cache/index.js:83:36 {
      input: '/graphql',
      code: 'ERR_INVALID_URL'
    }
  },
  extraInfo: undefined,
  page: '/'
}
error - ApolloError: Failed to parse URL from /graphql
    at new ApolloError (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/errors/errors.cjs:34:28)
    at /Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/core/core.cjs:1853:19
    at both (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/utilities/utilities.cjs:1072:53)
    at /Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/utilities/utilities.cjs:1065:72
    at new Promise (<anonymous>)
    at Object.then (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/utilities/utilities.cjs:1065:24)
    at Object.error (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/utilities/utilities.cjs:1073:49)
    at notifySubscription (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/zen-observable/lib/Observable.js:140:18)
    at onNotify (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/zen-observable/lib/Observable.js:179:3)
    at SubscriptionObserver.error (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/zen-observable/lib/Observable.js:240:7)
    at /Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/utilities/utilities.cjs:1055:68
    at Array.forEach (<anonymous>)
    at iterateObserversSafely (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/utilities/utilities.cjs:1055:25)
    at Object.error (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/utilities/utilities.cjs:1159:21)
    at notifySubscription (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/zen-observable/lib/Observable.js:140:18)
    at onNotify (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/zen-observable/lib/Observable.js:179:3)
    at SubscriptionObserver.error (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/zen-observable/lib/Observable.js:240:7)
    at handleError (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/link/http/http.cjs:296:67)
    at /Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/link/http/http.cjs:582:48 {
  graphQLErrors: [],
  clientErrors: [],
  networkError: TypeError: Failed to parse URL from /graphql
      at Object.fetch (node:internal/deps/undici/undici:11413:11) {
    [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
        at new NodeError (node:internal/errors:399:5)
        at URL.onParseError (node:internal/url:566:9)
        at new URL (node:internal/url:646:5)
        at new Request (node:internal/deps/undici/undici:7002:25)
        at fetch2 (node:internal/deps/undici/undici:10554:25)
        at Object.fetch (node:internal/deps/undici/undici:11411:18)
        at fetch (node:internal/process/pre_execution:230:25)
        at /Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/link/http/http.cjs:570:13
        at new Subscription (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/zen-observable/lib/Observable.js:197:34)
        at Observable.subscribe (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/zen-observable/lib/Observable.js:279:14)
        at Object.complete (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/utilities/utilities.cjs:1184:43)
        at Concast.start (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/utilities/utilities.cjs:1211:23)
        at new Concast (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/utilities/utilities.cjs:1203:19)
        at QueryManager.getObservableFromLink (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/core/core.cjs:1788:35)
        at QueryManager.getResultsFromLink (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/core/core.cjs:1828:40)
        at resultsFromLink (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/core/core.cjs:2005:58)
        at QueryManager.fetchQueryByPolicy (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/core/core.cjs:2031:21)
        at fromVariables (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/core/core.cjs:1879:40)
        at QueryManager.fetchQueryObservable (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/core/core.cjs:1894:15)
        at QueryManager.fetchQuery (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/core/core.cjs:1497:21)
        at QueryManager.query (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/core/core.cjs:1582:21)
        at ApolloClient.query (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/@apollo/client/core/core.cjs:2203:34)
        at getServerSideProps (webpack-internal:///./pages/index.tsx:192:84)
        at /Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/next/dist/server/render.js:508:110
        at /Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/next/dist/server/lib/trace/tracer.js:66:32
        at NoopContextManager.with (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7054)
        at ContextAPI.with (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:517)
        at NoopTracer.startActiveSpan (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18022)
        at ProxyTracer.startActiveSpan (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18782)
        at runWithContext (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/next/dist/server/lib/trace/tracer.js:60:164)
        at NextTracerImpl.trace (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/next/dist/server/lib/trace/tracer.js:61:16)
        at Object.renderToHTML (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/next/dist/server/render.js:508:51)
        at async doRender (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/next/dist/server/base-server.js:809:34)
        at async cacheEntry1.responseCache.get.incrementalCache.incrementalCache (/Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/next/dist/server/base-server.js:929:28)
        at async /Users/rubyke/项目/WebStormProjects/koktohay-next-main/node_modules/next/dist/server/response-cache/index.js:83:36 {
      input: '/graphql',
      code: 'ERR_INVALID_URL'
    }
  },
  extraInfo: undefined,
  page: '/'
}


是否还要在哪里配置strapi的地址

**Comment by darmau** [comment]
看起来是因为没有安装pnpm导致的。我没有用npm，用的是pnpm，先安装一下
